### ISSUE TITLE
merging is not working

### ISSUE THREAD

**Issue by kielfriedt** [nikku/merge-me#12]
I have authorized the app and do have branch protection setup. I have not seen the bot merge anything at this point. How might I debug it? Am I suppose to see it in the checks of the PR?

**Comment by nikku** [comment]
You can [setup the bot yourself locally](https://github.com/nikku/merge-me#setup) to debug the issue, yes.

If you would like me to help you, providing a little bit more feedback (i.e. on the branch protection setup, activated checks and the status of your PR) would be helpful.

I cannot help you otherwise without a little more context.

**Comment by kielfriedt** [comment]
simple setup:
develop 
1 review required

I have a PR with one review which is approved. 

Trying to debug it and i've removed all complexity for the Branch protection. Does the bot run every N mins or how do i trigger it?

BTW cloning and running npm install:
Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v79-darwin-x64.tar.gz

**Comment by nikku** [comment]
Please share a screenshot of your branch setup.

Please share a screenshot of your PR with all details visible.

**Comment by nikku** [comment]
> Trying to debug it and i've removed all complexity for the Branch protection. Does the bot run every N mins or how do i trigger it?

The bot gets triggered by GitHub webhook events, like most bots do. You should therefore see near immediate results or no results at all.

> BTW cloning and running npm install:
> Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v79-darwin-x64.tar.gz

`fsevents`, the dependency that fails to install, is a well known library that is only used on MacOS. 
Please also consult your favorite search engine on this matter. 

Cloning and installing works for me (on Linux):


```
git clone git@github.com:nikku/merge-me.git temp-merge-me
cd temp-merge-me
npm install
```

It also worked for a contributor last week on MacOS.

In general, please share the full context required. Otherwise we'll both only waste our time.

**Comment by kielfriedt** [comment]
I have both your app from the marketplace and a local running. I have no output from the local after the initial setup. 

Typically I see bots in the checks, is this where I should see yours running? I see probot-auto-merge running in the checks on some projects. It does provide a reason why it fails to merge. But I am also having issues running it on all my repos.

![PR](https://user-images.githubusercontent.com/552747/83604782-94644f00-a52b-11ea-851d-531cb5c360a8.png)
![branch-protection](https://user-images.githubusercontent.com/552747/83604786-96c6a900-a52b-11ea-8de2-a43c4b1661da.png)

**Comment by nikku** [comment]
> Typically I see bots in the checks, is this where I should see yours running?

The bot does not check anything. Instead it _just merges_ once everything is fine.

> Thanks for sharing these details. It looks indeed like the bot should work, out of the box.

What is your configured merge strategy? Is it `merge`? If that is the case, that would explain why `merge-me` does not work. Supporting other strategies than `rebase` is an open improvement (https://github.com/nikku/merge-me/issues/10).

**Comment by nikku** [comment]
If you've set up the bot locally, created a GitHub app via the workflow _and_ connected that app to your repository you should see detailed debug information flying in.

Just start the bot with

```
LOG_LEVEL=debug npm start
```

If you do not see anything as you changed your PR, that is the sign that you did not properly setup the bot / wire it with your repository.

**Comment by kielfriedt** [comment]
> > Typically I see bots in the checks, is this where I should see yours running?
> 
> The bot does not check anything. Instead it _just merges_ once everything is fine.
> 
> > Thanks for sharing these details. It looks indeed like the bot should work, out of the box.
> 
> What is your configured merge strategy? Is it `merge`? If that is the case, that would explain why `merge-me` does not work. Supporting other strategies than `rebase` is an open improvement (#10).
I have all merging types are available. Do I need to only allow rebase?
![merge](https://user-images.githubusercontent.com/552747/83700207-13ed2f00-a5bb-11ea-9695-fe476cf8b36f.png)

**Comment by kielfriedt** [comment]
> > > Typically I see bots in the checks, is this where I should see yours running?
> > 
> > 
> > The bot does not check anything. Instead it _just merges_ once everything is fine.
> > > Thanks for sharing these details. It looks indeed like the bot should work, out of the box.
> > 
> > 
> > What is your configured merge strategy? Is it `merge`? If that is the case, that would explain why `merge-me` does not work. Supporting other strategies than `rebase` is an open improvement (#10).
 
I have all merging types are available. Do I need to only allow rebase?

 ![merge](https://user-images.githubusercontent.com/552747/83700207-13ed2f00-a5bb-11ea-9695-fe476cf8b36f.png)

**Comment by kielfriedt** [comment]
I deleted my old fork and reforked it since my refs looked off. I made the same changes and got my test user to approve the PR. I got a 405 on merge.

00:29:35.078Z DEBUG event: branch is protected, skipping merge check (id=<redacted>)
00:29:35.078Z DEBUG event: attempting to merge #20 (id=<redacted>)
00:29:54.402Z DEBUG github: GitHub request: PUT /repos/:owner/:repo/pulls/:number/merge - 405 (installation=<redacted>)
  params: {
    "baseUrl": "https://api.github.com",
    "mediaType": {
      "format": "",
      "previews": []
    },
    "request": {
      "validate": {
        "commit_message": {
          "type": "string"
        },
        "commit_title": {
          "type": "string"
        },
        "merge_method": {
          "enum": [
            "merge",
            "squash",
            "rebase"
          ],
          "type": "string"
        },
        "number": {
          "required": true,
          "type": "integer"
        },
        "owner": {
          "required": true,
          "type": "string"
        },
        "repo": {
          "required": true,
          "type": "string"
        },
        "sha": {
          "type": "string"
        }
      },
      "retries": 3,
      "retryAfter": 16,
      "retryCount": 4
    },
    "owner": "<redacted>",
    "repo": "circleci_test",
    "number": 20,
    "sha": "<redacted>",
    "merge_method": "rebase"
  }
00:29:54.403Z DEBUG event: merge #20 failed (status=405) (id=<redacted>)
00:29:54.403Z  INFO event: skipping: failed to merge #20 (id=<redacted>)

**Comment by nikku** [comment]
You may review the status codes and their meaning in the [GitHub API docs](https://developer.github.com/v3/repos/merging/).

`405 - NOT ALLOWED` means that for whatever reason the bot is not allowed to merge.

**Comment by nikku** [comment]
Actually the documentation does not mention the 405. But that is what I've found while investigating.

**Comment by nikku** [comment]
I've added verbose logging on the merge error via https://github.com/nikku/merge-me/commit/a60b78eeb7efda1f04fdc7898c7ba5a44398cd2b.

Honestly I'm lost at this point why your org / setup would reject the merge.

**Comment by kielfriedt** [comment]
03:50:05.344Z DEBUG event: branch is protected, skipping merge check (id=)
03:50:05.345Z DEBUG event: attempting to merge #20 (id=)
03:50:05.345Z DEBUG event: (id=)
  merge #20 failed (status=undefined) TypeError: Cannot read property 'merge' of undefined
      at merge (/Users/<>/temp-merge-me/lib/core.js:463:42)
      at checkMerge (/Users/<>/temp-merge-me/lib/core.js:504:24)
03:50:05.345Z  INFO event: skipping: failed to merge #20 (id=)

**Comment by nikku** [comment]
That is a different issue, introduced by recent events.

Please double check again with the latest master. You should now see the actual merge failure reason in your logs, even without debug logging:

```
06:58:03.850Z  INFO event: merge #7 failed (message=This branch can't be rebased, status=405) (id=db07a400-a6f9-11ea-95cc-9ec3d11a4b54)
06:58:03.850Z  INFO event: skipping: failed to merge #7 
```

**Comment by kielfriedt** [comment]
I was able to get it to merge. But when I added on a restrictions on who can merge it fails. Even when I add myself or the bot it still says its not authorized to merge branch. Im just going to give up at this point.

**Comment by nikku** [comment]
Thanks for the notice.
